name: Flutter CI

on:
  pull_request:
    paths:
      - 'telegram_summarizer/**'
      - '.github/workflows/flutter-ci.yml'

jobs:
  analyze_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.x'
          channel: 'stable'

      - name: Flutter version
        run: flutter --version

      - name: Pub get
        working-directory: telegram_summarizer
        run: flutter pub get

      - name: Analyze
        working-directory: telegram_summarizer
        run: flutter analyze

      - name: Test
        working-directory: telegram_summarizer
        run: flutter test --no-pub
